version: "3.3"
# This compose file is for development environment. For production use only Dockerfile

services:
  app:
    env_file:
      - .env
    build: .
    command: bash -c "npm run dev-start"
    volumes: 
      - .:/code
    ports:
      - "8080:8080"
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:12
    env_file:
      - .db.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: {} 