name: deploy-staging
on:
  push:
      branches:
        - 'development'

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install Heroku Cli
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: ${{secrets.docker_username}}
        password: ${{secrets.docker_password}}
      
    - name: Heroku netrc file
      run: |
        cat >~/.netrc <<EOF
        machine api.heroku.com
            login ${{secrets.email}}
            password ${{secrets.api_key}}
        machine git.heroku.com
            login ${{secrets.email}}
            password ${{secrets.api_key}}
        EOF
        
        heroku login

    
    - name: Heroku registry login
      run: |
        heroku container:login
        
    - name: Clean registry
      run: |
        heroku container:rm web release --app=api-corona-jobs-staging
      
    - name: Build and push image
      run: |
        heroku container:push web release --recursive --app=api-corona-jobs-staging

    - name: Release
      run: |
        heroku container:release web release --app=api-corona-jobs-staging
        
